version: 2

models:
  - name: fct_per_brand_daily_sales
    description: "Daily Sales for every brand"
    tests:
    - dbt_utils.unique_combination_of_columns:
        combination_of_columns:
        - order_date
        - brand_name

  - name: fct_per_country_daily_sales
    description: "Daily Sales for every country"
    columns:
    - name: country
      tests:
      - not_null